### PR TITLE
unbreak pencil/pen toggle hotkey on MacOS

### LINKED ISSUE #27: Toggle pencil/pen hotkey not working (MacOS Chrome)
Typing alt+p on MacOS inserts a literal π key, and does not toggle pencil/pen.

I suspect this would be fixed by adding `e.preventDefault()` here:
https://github.com/nelhage/crossme/blob/master/imports/components/puzzle.jsx#L217

### PR DESCRIPTION
**Pull request by jlindberg-oss**
FWIW KeyboardEvent's code property [1] would be better suited to handle this
but it has no support on IE or Edge so it'd require a polyfill.

[1] https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code

Fixes #27

### CODE REVIEW

File: imports/components/puzzle.jsx [hunk 1]
```diff
@@ -213,8 +213,11 @@ class Puzzle extends React.Component {
       return;
     }
 
-    if (e.altKey && e.key === 'p') {
+    // On MacOS, the altKey modifier has been applied to the key already
+    // before it gets sent to the keyDown, so 'p' is already 'π'.
+    if (e.altKey && (e.key === 'p' || e.key === 'π')) {
       this.delegate.togglePencil();
+      e.stopPropagation();
```
Comment (jlindberg-oss) [inline imports/components/puzzle.jsx]: I expected this to need `preventDefault` but it needed `stopPropagation` instead.  I didn't go source-diving but presumably the reason is that the actual insertion of characters onto the puzzle is handled by some other event handler, vs being handled by a native input element.

**Comment by nelhage** [comment]
Thanks!
